// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    [Migration("20260905183824_AddVendorTableAndConfirmationFlow")]
    partial class AddVendorTableAndConfirmationFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.MaterialEstimationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MaterialEstimationReviews");
                });

            modelBuilder.Entity("Backend.Models.MaterialEstimationReviewItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AiEstimatedQuantity")
                        .HasColumnType("numeric");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("FinalQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MaterialEstimationReviewId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialEstimationReviewId");

                    b.ToTable("MaterialEstimationReviewItems");
                });

            modelBuilder.Entity("Backend.Models.MaterialRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExcludedSupplierIds")
                        .HasColumnType("text");

                    b.Property<bool>("GeneratedByAi")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityRequested")
                        .HasColumnType("numeric");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedSupplierId")
                        .HasColumnType("text");

                    b.Property<string>("SelectedSupplierName")
                        .HasColumnType("text");

                    b.Property<decimal?>("SelectedSupplierPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("SelectedSupplierTelegramChatId")
                        .HasColumnType("text");

                    b.Property<decimal>("ShortageQuantity")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MaterialRequests");
                });

            modelBuilder.Entity("Backend.Models.ProcurementRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MaterialRequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierTelegramChatId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ProcurementRequests");
                });

            modelBuilder.Entity("Backend.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("DeliveredQuantity")
                        .HasColumnType("numeric");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MaterialRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("OrderedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcurementRequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentForConfirmationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierTelegramChatId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("VendorConfirmationStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VendorConfirmedQuantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("VendorRespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Backend.Models.SupplierPerformanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysLate")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnTime")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SupplierPerformanceRecords");
                });

            modelBuilder.Entity("Backend.Models.Vendor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChatId")
                        .HasColumnType("text");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReliabilityScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = "SUP-001",
                            DeliveryDays = 15,
                            MaterialCode = "CEMENT-001",
                            Name = "ABC Traders",
                            PricePerUnit = 12.50m,
                            Rating = 4.5m,
                            ReliabilityScore = 0.92m
                        },
                        new
                        {
                            Id = "SUP-002",
                            DeliveryDays = 10,
                            MaterialCode = "CEMENT-001",
                            Name = "FastBuild Supplies",
                            PricePerUnit = 14.00m,
                            Rating = 4.2m,
                            ReliabilityScore = 0.85m
                        },
                        new
                        {
                            Id = "SUP-003",
                            DeliveryDays = 45,
                            MaterialCode = "CEMENT-001",
                            Name = "CheapCo",
                            PricePerUnit = 9.00m,
                            Rating = 3.5m,
                            ReliabilityScore = 0.70m
                        },
                        new
                        {
                            Id = "SUP-004",
                            DeliveryDays = 5,
                            MaterialCode = "CEMENT-001",
                            Name = "Premium Materials Inc",
                            PricePerUnit = 25.00m,
                            Rating = 4.9m,
                            ReliabilityScore = 0.98m
                        },
                        new
                        {
                            Id = "SUP-005",
                            DeliveryDays = 12,
                            MaterialCode = "CEMENT-001",
                            Name = "Reliable Cement Co",
                            PricePerUnit = 13.00m,
                            Rating = 4.3m,
                            ReliabilityScore = 0.88m
                        });
                });

            modelBuilder.Entity("Backend.Models.MaterialEstimationReviewItem", b =>
                {
                    b.HasOne("Backend.Models.MaterialEstimationReview", null)
                        .WithMany("Items")
                        .HasForeignKey("MaterialEstimationReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.MaterialEstimationReview", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
